// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string leaderboard_level_3 = "CgkI-eugvo4GEAIQBA"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkI-eugvo4GEAIQAw"; // <GPGSID>
        public const string leaderboard_level_1 = "CgkI-eugvo4GEAIQAg"; // <GPGSID>
        public const string leaderboard_tutorial = "CgkI-eugvo4GEAIQAQ"; // <GPGSID>
        public const string leaderboard_level_6 = "CgkI-eugvo4GEAIQBw"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkI-eugvo4GEAIQBg"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkI-eugvo4GEAIQBQ"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkI-eugvo4GEAIQCA"; // <GPGSID>
        public const string leaderboard_level_8 = "CgkI-eugvo4GEAIQCQ"; // <GPGSID>
        public const string leaderboard_level_9 = "CgkI-eugvo4GEAIQCg"; // <GPGSID>

}

